name: Cargo Build & Test

on:
  push:
    branches:
      - master
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
          
      - name: Rust Check
        run: rustup --version

      - name: Cargo Check
        run: cargo --version

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose -- --nocapture
        